definitions:
  contractaddress.ContractAddressResponse:
    properties:
      address:
        type: string
    type: object
  errorhandler.ErrorResponse:
    properties:
      error:
        type: string
      error_detail:
        type: string
      status:
        type: integer
    type: object
  healthcheck.healthCheckResponse:
    properties:
      message:
        type: string
    type: object
  hello.helloWorldResponse:
    properties:
      message:
        type: string
    type: object
  product.CreateProductRequest:
    properties:
      description:
        type: string
      image_url:
        type: string
      name:
        type: string
      price:
        type: integer
      sku:
        type: string
      stock:
        type: integer
    required:
    - description
    - image_url
    - name
    - price
    - sku
    - stock
    type: object
host: localhost:8080
info:
  contact: {}
  description: Geth DAPP DEMO
  title: Geth DAPP DEMO
  version: "1.0"
paths:
  /api/health-check:
    get:
      consumes:
      - application/json
      description: Check the server communication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.healthCheckResponse'
      summary: Health Check
      tags:
      - healthCheck
  /api/v1/contract-address:
    get:
      consumes:
      - application/json
      description: Get Contract Address
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contractaddress.ContractAddressResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorhandler.ErrorResponse'
      summary: Get Contract Address
      tags:
      - contractAddress
  /api/v1/hello:
    get:
      consumes:
      - application/json
      description: Smart Contract demo.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hello.helloWorldResponse'
      summary: Hello World
      tags:
      - helloWorld
  /api/v1/products:
    post:
      consumes:
      - application/json
      description: Create NFT product.
      parameters:
      - description: New product info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/product.CreateProductRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorhandler.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errorhandler.ErrorResponse'
      summary: Create product.
      tags:
      - product
swagger: "2.0"
