openapi: 3.0.0
info:
  contact: {}
  description: Geth DAPP DEMO
  title: Geth DAPP DEMO
  version: "1.0"
paths:
  /api/health-check:
    get:
      description: Check the server communication.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthcheck.healthCheckResponse"
      summary: Health Check
      tags:
        - healthCheck
  /api/v1/contract-address:
    get:
      description: Get Contract Address
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/contractaddress.contractAddressResponse"
      summary: Get Contract Address
      tags:
        - contractAddress
  /api/v1/hello:
    get:
      description: Smart Contract demo.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/hello.helloWorldResponse"
      summary: Hello World
      tags:
        - helloWorld
servers:
  - url: //localhost:8080
components:
  schemas:
    contractaddress.contractAddressResponse:
      properties:
        address:
          type: string
      type: object
    healthcheck.healthCheckResponse:
      properties:
        message:
          type: string
      type: object
    hello.helloWorldResponse:
      properties:
        message:
          type: string
      type: object
