openapi: 3.0.0
info:
  contact: {}
  description: Geth DAPP DEMO
  title: Geth DAPP DEMO
  version: "1.0"
paths:
  /api/health-check:
    get:
      description: Check the server communication.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthcheck.healthCheckResponse"
      summary: Health Check
      tags:
        - healthCheck
  /api/v1/contract-address:
    get:
      description: Get Contract Address
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/contractaddress.ContractAddressResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorhandler.ErrorResponse"
      summary: Get Contract Address
      tags:
        - contractAddress
  /api/v1/hello:
    get:
      description: Smart Contract demo.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/hello.helloWorldResponse"
      summary: Hello World
      tags:
        - helloWorld
  /api/v1/products:
    post:
      description: Create NFT product.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/product.CreateProductRequest"
        description: New product info
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorhandler.ErrorResponse"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorhandler.ErrorResponse"
      summary: Create product.
      tags:
        - product
servers:
  - url: //localhost:8080
components:
  schemas:
    contractaddress.ContractAddressResponse:
      properties:
        address:
          type: string
      type: object
    errorhandler.ErrorResponse:
      properties:
        error:
          type: string
        error_detail:
          type: string
        status:
          type: integer
      type: object
    healthcheck.healthCheckResponse:
      properties:
        message:
          type: string
      type: object
    hello.helloWorldResponse:
      properties:
        message:
          type: string
      type: object
    product.CreateProductRequest:
      properties:
        description:
          type: string
        image_url:
          type: string
        name:
          type: string
        price:
          type: integer
        sku:
          type: string
        stock:
          type: integer
      required:
        - description
        - image_url
        - name
        - price
        - sku
        - stock
      type: object
